disabled = false
languageCode = 'en-US'
languageName = 'English'
title = ''
copyright = """Designed with [Hugo](https://gohugo.io/)
 Licensed under [MIT license](https://github.com/ololiuhqui/magnolia-free-hugo-theme/blob/main/LICENSE.md) 📄"""
contentDir = "content/en"

[params]
  subtitle = "data processing services"
  
  [params.homepage]
    preTitle = 'andalytics by'
    title = "marijana andabaka"
    intro= """
### Advanced data science solutions: From data to discoveries
___

PhD forest scientist specializing in data science workflows, automated analysis, 
and research insights for research institutions and organizations. Core expertise:

- **Statistical modeling & data science** for ecological and forestry research
- **Spatial data integration** (GIS, remote sensing, automated processing)
- **R programming & automation** for scalable research workflows  
- **Climate & environmental data** analytics and visualization

With a PhD in Forestry and 7+ years of research experience, I help organizations transform complex environmental data into actionable insights 
for research, management, and policy decisions.
        """
    mainButton = "Services"
    mainButtonRef = "pages/services"
    secondButton = "Contact"
    secondButtonRef = "/contacts"
    blogTitle = "Forest Data Science"
    blogButton= "More Posts"

[params.office]
  title = "Forest Data Science"
  description = "Insights on research data analysis, automation, and forest science"

[params.contacts]
  title = "Let's Discuss Your Research"
  formCallToAction = "Send an inquiry about your research project"
  socialCallToAction = "Connect with me on professional networks"
  [params.contacts.form]
    formspreeLink = "https://formspree.io/f/xrbezdlz"
    firstname = "Firstname*"
    lastname = "Lastname*"
    email = "E-mail*"
    phone = "Phone Number*"
    Inquiry = "Tell me about your research needs*"
    checkbox = "I accept that my data will be processed in accordance with privacy regulations*"
    submitBtn = "Send Inquiry"

[params.services]
  title = "Forest Data Science Services"
  description = """Advanced statistical analysis and R solutions for forestry and ecological research.
  
  Combining PhD-level forest science expertise with sophisticated analytical methods to transform complex datasets into actionable research insights.""" 
  
  [params.services.list]
    [params.services.list.0]
      title = "Statistical Analysis & Modeling"
      description = "Advanced statistical approaches for complex ecological and forestry datasets. Services include mixed-effects modeling, multivariate analysis, time series analysis, and spatial statistics. I develop methodologically rigorous analyses that address your specific research questions while accounting for the complexities inherent in ecological data. All analyses are designed to support peer-reviewed publication and scientific decision-making."
    
    [params.services.list.01]
      title = "Spatial Data Integration"
      description = "Integration and analysis of spatial datasets including field measurements, remote sensing, GIS data, and environmental variables. I specialize in combining multiple spatial data sources and working with geographic information to support forest research questions."
    
   [params.services.list.02]
     title = "Climate-Forest Interactions"
     description = "Analysis of climate impacts on forest ecosystems using integrated climate and ecological datasets. Services include climate change impact assessments, vulnerability analysis, and long-term trend analysis. I specialize in linking climate variables with forest responses, from individual tree growth to ecosystem-level changes, providing insights crucial for adaptive forest management."
    
   [params.services.list.03]
     title = "Research Workflow Development"
     description = "Creation of reproducible R workflows tailored to your research needs. I develop comprehensive analytical pipelines that ensure methodological consistency and scientific transparency. Services include custom R script development, automated reporting systems, and training programs that build your team's analytical capacity."
    [params.services.list.04]
      title = "Scientific Visualization & Communication"
      description = "Development of publication-quality visualizations that effectively communicate complex research findings. Services include advanced statistical graphics, interactive dashboards and data science applications. I specialize in creating visualizations that not only meet publication standards but also enhance scientific understanding and facilitate research communication."
[params.socials]
  enabled = true
  callToAction = "Connect on professional networks >"
      [[params.socials.link]]
        name = "github"
        link = "https://github.com/andabaka"
      [[params.socials.link]]
        name = "linkedin"
        link = "https://www.linkedin.com/in/marijana-andabaka/"
      [[params.socials.link]]
        name = "googlescholar"
        link = "https://scholar.google.hr/citations?user=awNSPV8AAAAJ&hl=en"

[params.schedules]
  enabledFooter = false
  enabledContacts = false
  title = "Office hours"
  [params.schedules.days]
    day1 = ""
    day2 = ""
    day3 = ""
    day4 = ""
    day5 = ""
    day6 = ""
    day7 = ""

[params.footer]
  extraDescription1 = "Data Analysis Services for Research Institutions"
  extraDescription2 = ""
  [params.footer.navigate]
  heading = "Navigate"   
  [params.footer.contacts]
  enabled = true
  heading = "Contact"
  address = "Ivana Pintarica 30, Ivanec Bistranski 10290, Croatia"
  mail = "marijana@andalytics.com"
  mail2 = ""
  phone = ""
  
[params.notfound]
  title = "404, page not found"

[params.single]
  similarContent= "Similar Content"
  toc= "Table of Contents"

[menus]
  [[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 1
  [[menus.main]]
  name = "Services"
  pageRef = "pages/services"
  weight = 2
  [[menus.main]]
  name = "Forest Data Science"
  pageRef = "/posts"
  weight = 3
  [[menus.main]]
  name = "Contact"
  pageRef = "pages/contacts"
  weight = 4