baseURL = 'https://andalytics.com/'
languageCode = 'en'
title = 'Andalytics'
defaultContentLanguage = 'en'
defaultContentLanguageInSubDir = false
enableRobotsTXT = true
theme = "Magnolia"
googleAnalytics = "G-NDC3LQZ6DM"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  custom_css = ["css/custom.css"]

[taxonomies]
  tag = "tags"


[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  
  [module.hugoVersion]
    extended = false
    min = '0.129.0'

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = false
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      linkify = true
    [markup.goldmark.parser]
      autoHeadingID = true
      attribute = true