[build]
publish = "public"
command = "hugo --ignoreDeprecated"  # dodajemo flag za ignoriranje deprecated upozorenja

[context.production.environment]
HUGO_VERSION = "0.139.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --ignoreDeprecated"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --ignoreDeprecated"