disabled = false
languageCode = 'en-US'
languageName = 'English'
title = ''
copyright = """Designed with [Hugo](https://gohugo.io/)
 Licensed under [MIT license](https://github.com/ololiuhqui/magnolia-free-hugo-theme/blob/main/LICENSE.md) 📄"""
contentDir = "content/en"

[params]
  subtitle = "data processing services"
  
  [params.homepage]
    preTitle = 'andalytics by'
    title = "marijana andabaka"
    intro= """
### Transform your research data processing from months to hours
___

Specialized in automating data analysis for research institutions with extensive expertise in forest science.
Expertise in:
- **R Programming** for research workflow automation
- **Forest Ecosystems** data analysis
- **Spatial data** integration
- **Climate data** processing

With a PhD in Forestry and 7 years of academic research experience, I understand the challenges of your research data processing.
        """
    mainButton = "Services"
    mainButtonRef = "pages/services"
    secondButton = "Contact"
    secondButtonRef = "/contacts"
    blogTitle = "Blog Posts"
    blogButton= "More Posts"

[params.office]
  title = "Insights on research data analysis, automation, and forest science"
  description = "Blog"

[params.contacts]
  title = "Let's Discuss Your Research"
  formCallToAction = "Send an inquiry about your research project"
  socialCallToAction = "Connect with me on professional networks"
  [params.contacts.form]
    formspreeLink = "https://formspree.io/f/xrbezdlz"
    firstname = "Firstname*"
    lastname = "Lastname*"
    email = "E-mail*"
    phone = "Phone Number*"
    Inquiry = "Tell me about your research needs*"
    checkbox = "I accept that my data will be processed in accordance with privacy regulations*"
    submitBtn = "Send Inquiry"

[params.services]
  title = "Research Data Analysis Services"
  description = """Specialized in transforming complex research data into actionable scientific insights.
  
  Offering expertise in forest science research while supporting diverse research institutions with data analysis automation.""" 

  [params.services.list]
    [params.services.list.0]
      title = "Research Automation"
      description = "Transform time-consuming manual data processing into efficient automated workflows. I develop custom solutions that streamline your research processes while maintaining rigorous quality standards. Services include automated data cleaning, standardization of research protocols, batch processing of large datasets, and creation of reproducible analysis pipelines. This automation significantly reduces analysis time and human error, allowing researchers to focus on interpretation and discovery."
    
    [params.services.list.01]
      title = "R Programming Solutions"
      description = "Custom R script development designed to address your specific research challenges. I create comprehensive solutions that include efficient data processing workflows, robust statistical analysis functions, and dynamic data visualizations. Each solution is built with reproducibility in mind and comes with thorough documentation and ongoing support. Whether you're working with time series, spatial data, or complex hierarchical datasets, I can help streamline your analysis process."
    
    [params.services.list.02]
      title = "Forest Research Analysis"
      description = "Comprehensive analysis solutions for forest science research, combining inventory data, remote sensing, and environmental parameters. Services include processing of forest measurement data, tree growth analysis, forest health assessment, and ecosystem monitoring. Specialized in integrating multiple data sources to provide deeper insights into forest dynamics and responses to environmental changes."
    
   [params.services.list.03]
     title = "Spatial Data Processing"
     description = "Advanced analysis of spatial research data, with expertise in forest ecosystem analysis. Services include processing of various spatial data formats, satellite imagery, integration of field measurements with remote sensing data, creating spatial analysis workflows, and developing automated mapping solutions. Specialized in analyzing forest structure and temporal changes through comprehensive geospatial analytics."
    
   [params.services.list.04]
     title = "Climate Data Integration"
     description = "Expert processing and analysis of climate data in research contexts. Services include integration of climate variables with field measurements, analysis of climate impacts on forest ecosystems, and development of automated monitoring systems. Specialized in linking climate data with various aspects of forest ecosystems, from tree growth and vitality to stand dynamics and long-term ecosystem changes."
    
    [params.services.list.05]
      title = "Research Visualization"
      description = "Creation of publication-quality data visualizations that effectively communicate research findings. Services include development of custom plotting functions, interactive visualization tools, and automated report generation. Specialized in visualizing complex multi-variable relationships. All visualizations are reproducible and easily updatable with new data."

[params.socials]
  enabled = true
  callToAction = "Connect on professional networks >"
      [[params.socials.link]]
        name = "github"
        link = "https://github.com/andabaka"
      [[params.socials.link]]
        name = "linkedin"
        link = "https://www.linkedin.com/in/marijana-andabaka/"
      [[params.socials.link]]
        name = "googlescholar"
        link = "https://scholar.google.hr/citations?user=awNSPV8AAAAJ&hl=en"

[params.schedules]
  enabledFooter = false
  enabledContacts = false
  title = "Office hours"
  [params.schedules.days]
    day1 = ""
    day2 = ""
    day3 = ""
    day4 = ""
    day5 = ""
    day6 = ""
    day7 = ""

[params.footer]
  extraDescription1 = "Data Analysis Services for Research Institutions"
  extraDescription2 = ""
  [params.footer.navigate]
  heading = "Navigate"   
  [params.footer.contacts]
  enabled = true
  heading = "Contact"
  address = "Ivana Pintarica 30, Ivanec Bistranski 10290, Croatia"
  mail = "marijana@andalytics.com"
  mail2 = ""
  phone = ""
  
[params.notfound]
  title = "404, page not found"

[params.single]
  similarContent= "Similar Content"
  toc= "Table of Contents"

[menus]
  [[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 1
  [[menus.main]]
  name = "Services"
  pageRef = "pages/services"
  weight = 2
  [[menus.main]]
  name = "Blog"
  pageRef = "posts"
  weight = 3
  [[menus.main]]
  name = "Contact"
  pageRef = "pages/contacts"
  weight = 4